### PR TITLE
Add root entity annotation

### PR DESCRIPTION
**Pull request by cthoyt**
Related to https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2149

### CODE REVIEW

**Comment by matentzn** [comment]
How did you determine that this is the proper root?

**Comment by cthoyt** [comment]
1. I looked at the results for BSPO from my automated analysis https://cthoyt.com/cob-root-analysis/#bspo
2. I found that the edit file actually had some rearrangement going on, so while I was browsing in protege I realized that all BSPO terms had this as a common ancestor

**Comment by matentzn** [comment]
Niiiiiice analysis table man!!! 

I will get this merged but need some feedback from @balhoff to be sure.

**Comment by cthoyt** [comment]
yeah agreed, I was pretty confused by this too so @balhoff you can feel free to change this PR however you'd like.

**Review by balhoff — APPROVED** [review]

**Comment by balhoff** [comment]
I think that looks good, thanks!

**Comment by cthoyt** [comment]
@balhoff its also possible to annotate more than 1 root or we can go deeper and expose BSPO terms too, what do you think?

**Comment by balhoff** [comment]
I think 'anatomical entity' is tidy.

**Pull request merged**
